Develop
kulloveth/WellnessCity pull request #24
Opened 2020-10-15 23:17 UTC by datcodeboy

I added the navigation_graph and fragments for the splash screen and onboarding screen

2020-10-15 23:53 UTC, kulloveth requested changes
you should checkout changes that I made and fix the lines I pointed out then complete the feature, also for future PR branch out with a new name to avoid altering develop or master

2020-10-15 23:53 UTC, kulloveth commented on app/build.gradle
> +    def nav_version = "2.3.1"
this should move to the project level gradle

2020-10-15 23:53 UTC, kulloveth commented on app/src/main/java/com/wellnesscity/health/OnboardingFragment.kt
> +        return inflater.inflate(R.layout.fragment_onboarding, container, false)
we are using viewbinding instead

2020-10-15 23:53 UTC, kulloveth commented on app/src/main/java/com/wellnesscity/health/SplashScreenFragment.kt
> +            navController!!.navigate(R.id.action_splashScreenFragment_to_onboardingFragment)
`!!` causes null pointer exception should be replaced with `?` and also we are using safeargs for navigation to avoid runtime error which I already added the dependency

2020-10-15 23:53 UTC, kulloveth commented on app/src/main/res/layout/fragment_onboarding.xml
> +</FrameLayout>
their is no need for framelayout lets maintain only constraint when there are more than one child view

2020-10-15 23:53 UTC, kulloveth commented on app/src/main/res/layout/fragment_splash_screen.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
this is best an imageView, we should avoid nested parent views

2020-10-15 23:53 UTC, kulloveth commented on app/src/main/res/navigation/nav_graph.xml
> +    app:startDestination="@id/onboardingFragment">
this should be splashfragment  instead

2020-10-15 23:59 UTC, kulloveth requested changes

2020-10-15 23:59 UTC, kulloveth commented on app/src/main/res/layout/fragment_onboarding.xml
> +        app:layout_constraintBottom_toTopOf="@id/buttonNext" />
also its best we use a library for indicator which I already added

2020-10-15 23:59 UTC, kulloveth commented on app/src/main/res/layout/fragment_onboarding.xml
> +        android:overScrollMode="never"
this is not advisable, it should be removed

2020-10-15 23:59 UTC, kulloveth commented on app/src/main/res/layout/fragment_onboarding.xml
> +        android:minWidth="110dp"
I dont know the reason for this minWidth dont think its necessary

2020-10-15 23:59 UTC, kulloveth commented on app/src/main/res/layout/fragment_onboarding.xml
> +        android:layout_marginBottom="10dp"
always add sizes to dimens file to avoid repetition, you will see a sample with what I have done

2020-10-16 11:46 UTC, datcodeboy reviewed
I will carry the new review

2025-03-24 01:31 UTC, closed without merging