Update to the SplashFragment
kulloveth/WellnessCity pull request #27
Opened 2020-10-16 11:48 UTC by datcodeboy

changes to the splash screen fragments

2020-10-16 14:02 UTC, kulloveth commented
is this ready for review

2020-10-16 14:58 UTC, datcodeboy commented
yes it is

2020-10-18 12:47 UTC, kulloveth requested changes

2020-10-18 12:47 UTC, kulloveth commented on app/src/main/res/layout/fragment_splash.xml
> +        android:background="@drawable/splash_screen" />
this is an imageView why not use the drawable as a src

2020-10-18 12:47 UTC, kulloveth commented on app/src/main/java/com/wellnesscity/health/ui/intro/SplashFragment.kt
> +            .navigate(R.id.action_splashFragment_to_onboardingFragment)
We are using safeArgs so the destination id should be in safeArg format

2020-10-18 12:47 UTC, kulloveth commented on app/src/main/java/com/wellnesscity/health/ui/intro/ViewPagerFragment.kt
> +class ViewPagerFragment : Fragment() {
no need for this class the onboardingFragment is there already

2020-10-18 12:47 UTC, kulloveth commented on app/src/main/java/com/wellnesscity/health/ui/intro/ViewPagerAdapter.kt
> +): FragmentStateAdapter(fm, lifecycle) {
We are using views only we dont need more fragments for this onboarding

2020-10-18 12:47 UTC, kulloveth commented on app/src/main/res/navigation/nav_graph.xml
> +    <fragment
this should go as well since we dont need it

2020-10-19 11:39 UTC, kulloveth reviewed
You forget to change the ViewPagerAdapter to use RecyclerAdapter, Also the direction to Onboarding fragment is still not using SafeArgs. Quickly fix this so I can merge

2020-10-23 09:45 UTC, merged